## КОНСПЕКТ ЛЕКЦИИ:


In [3]:
# ---про numpy---
import numpy as np
a = np.array([1,2,3,4,5])
print(type(a), a)
a = np.array([1.23, 2, 3, 4, 5])
print(type(a), a)

a = np.array([range(i, i+3) for i in [2, 4, 6]])
print(a, type(a))

a = np.zeros(10, dtype=int)
print(a, type(a))

print(np.ones((2, 5), dtype=float))

print(np.full((4, 5), 3.1415))

print(np.arange(0, 20, 2))

print(np.eye(4))


<class 'numpy.ndarray'> [1 2 3 4 5]
<class 'numpy.ndarray'> [1.23 2.   3.   4.   5.  ]
[[2 3 4]
 [4 5 6]
 [6 7 8]] <class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]]
[ 0  2  4  6  8 10 12 14 16 18]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
#---массивы---

np.random.seed(1)
x1 = np.random.randint(10, size=3)
print(x1)
x1 = np.random.randint(10, size=(3, 2))
print(x1)
x1 = np.random.randint(10, size=(3, 2, 1))
print(x1)

print(x1.ndim, x1.shape, x1.size)

a = np.array([1,2,3, 4, 5])
print(a[0])
print(a[-2])
a[1] = 20
print(a)
a = np.array([[1, 2], [3, 4]])
print(a[0,0])
a[1, 0] = 20
print(a)
a = np.array([1, 2, 3,4])
b = np.array([1.0, 2, 3,4])

a[0] = 10.123 # приведет к инту
print(a) 


[5 8 9]
[[5 0]
 [0 1]
 [7 6]]
[[[9]
  [2]]

 [[4]
  [5]]

 [[2]
  [4]]]
3 (3, 2, 1) 6
1
4
[ 1 20  3  4  5]
1
[[ 1  2]
 [20  4]]
[10  2  3  4]


In [23]:
#---срезы---
a = np.array([1, 2, 3, 4, 5, 6])
print(a[:3])
print(a[3:])
print(a[2:4])
print(a[::-1])

a = np.linspace(1, 12, 12)
print(a.reshape(2,6))

x = np.array([1, 2, 3])
y = np.array([4, 5])
z = np.array([6])
print(np.concatenate([x, y, z], axis=0))

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

r1 = np.vstack([x, y]) # ставится один на другой
print(r1)
print(np.hstack((r1, r1))) # склеиваются сбоку


[1 2 3]
[4 5 6]
[3 4]
[6 5 4 3 2 1]
[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [26]:
#---вычисления с массивами---
#векторизованная операция применяется независимо к каждому элементу

x = np.arange(10)
print(x)

print(x*2 + 1)

#универсальные функции
print(np.add(np.multiply(x, 2), 1))
# - - / // ** %

x = np.arange(5)
y = np.empty(5)
y2 = np.zeros(10)
print(np.multiply(x, 10, out=y)) # out - то куда запишется результат
print(np.multiply(x, 10, out=y2[::2]))

x = np.arange(1, 5)
print(x)
print(np.add.reduce(x)) #- свертка суммы всего массива

print(np.add.accumulate(x)) #- постепенная свертка. результат - в массив

x = np.arange(1, 10)
print(np.add.outer(x, x)) #- квадратная матрица с результатами сложения попарно всех элементов



[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0. 10. 20. 30. 40.]
[ 0. 10. 20. 30. 40.]
[1 2 3 4]
10
[ 1  3  6 10]
[[ 2  3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10 11]
 [ 4  5  6  7  8  9 10 11 12]
 [ 5  6  7  8  9 10 11 12 13]
 [ 6  7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14 15]
 [ 8  9 10 11 12 13 14 15 16]
 [ 9 10 11 12 13 14 15 16 17]
 [10 11 12 13 14 15 16 17 18]]
