## 1. Какие еще существуют коды типов? 



In [ ]:
маленькая буква - signed со знаком, большая - unsigned без знака.
Например:
'b' – целое число со знаком (signed char) (от -128 до 127).
'B' – целое число без знака (unsigned char) (от 0 до 255).
в остальных такая же логика
'h' – целое число со знаком (short) (от -32,768 до 32,767).
'H' – целое число без знака (unsigned short) (от 0 до 65,535).
'i' – целое число со знаком (int) (от -2,147,483,648 до 2,147,483,647).
'I' – целое число без знака (unsigned int) (от 0 до 4,294,967,295).
'l' – целое число со знаком (long) (от -2,147,483,648 до 2,147,483,647).
'L' – целое число без знака (unsigned long) (от 0 до 4,294,967,295).
непарные коды типов:
'f' – число с плавающей точкой (float).
'd' – число с двойной точностью (double).
'u' – символ (один Unicode символ).

## 2. Напишите код, подобный приведенному выше, но с другим типом


In [2]:
import array
import sys

# массив из одиночных символов
chars = array.array('u', ['a', 'b', 'c'])
print(chars)  
print(type(chars))
print(sys.getsizeof(chars)) 

array('u', 'abc')
<class 'array.array'>
86


## 3. Напишите код для создания массива с 5 значениями, располагающимися через равные интервалы в диапазоне от 0 до 1


In [5]:
import numpy as np
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


## 4. Напишите код для создания массива с 5 равномерно распределенными случайными значениями в диапазоне от 0 до 1


In [6]:
arr = np.random.uniform(0, 1, 5)
print(arr)

[0.70418672 0.90133389 0.04501854 0.85532485 0.53064686]


## 5. Напишите код для создания массива с 5 нормально распределенными случайными значениями с мат. ожиданием = 0 и дисперсией 1


In [8]:
arr = np.random.normal(0, 1, 5)
print(arr)

[-1.27714400e-01 -1.38783529e+00  3.35930548e-01  7.19860235e-01
  9.77856213e-04]


## 6. Напишите код для создания массива с 5 случайнвми целыми числами в от [0, 10)

In [9]:
arr = np.random.randint(0, 10, 5)
print(arr) # [1 7 8 1 3]


[9 7 2 0 7]


## 7. Написать код для создания срезов массива 3 на 4


In [11]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

## - первые две строки и три столбца
slice_1 = arr[:2, :3]
print(slice_1)

## - первые три строки и второй столбец
slice_2 = arr[:3, 1]
print(slice_2)

## - все строки и столбцы в обратном порядке
slice_3 = arr[::-1, ::-1]
print(slice_3)

## - второй столбец
slice_4 = arr[:, 1]
print(slice_4)

## - третья строка
slice_5 = arr[2]
print(slice_5)

[[1 2 3]
 [5 6 7]]
[ 2  6 10]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[ 2  6 10]
[ 9 10 11 12]



## 8. Продемонстрируйте, как сделать срез-копию


In [13]:
slice_copy = arr[:2, :3].copy()
print(slice_copy)

[[1 2 3]
 [5 6 7]]


## 9. Продемонстрируйте использование newaxis для получения вектора-столбца и вектора-строки

In [15]:
arr = np.array([1, 2, 3, 4, 5])

column_vector = arr[:, np.newaxis]
print(column_vector)


[[1]
 [2]
 [3]
 [4]
 [5]]


In [16]:
row_vector = arr[np.newaxis, :]
print(row_vector)


[[1 2 3 4 5]]


## 10. Разберитесь, как работает метод dstack
Метод dstack объединяет массивы вдоль третьей оси

In [17]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
result = np.dstack((arr1, arr2))
print(result)


[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


## 11. Разберитесь, как работают методы split, vsplit, hsplit, dsplit


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.split(arr, 3)  # Разделяет на 3 части
print(result)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.vsplit(arr, 3)  # Разделяет на 3 части по строкам
print(result)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.hsplit(arr, 3)  # Разделяет на 3 части по столбцам
print(result)


[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [22]:
arr = np.arange(27).reshape(3, 3, 3)
print(arr)
result = np.dsplit(arr, 3)  # Разделяет по третьей оси (по глубине)
print(result)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]]), array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]],

       [[19],
        [22],
        [25]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]],

       [[20],
        [23],
        [26]]])]


## 12. Привести пример использования всех универсальных функций, которые я привел

In [23]:
np.add([1, 2], [3, 4])


array([4, 6])

In [24]:
np.subtract([5, 6], [3, 2])


array([2, 4])

In [26]:
x = np.arange(5)
y = np.empty(5)
y2 = np.zeros(10)
print(np.multiply(x, 10, out=y)) # out - то куда запишется результат
print(np.multiply(x, 10, out=y2[::2]))


[ 0. 10. 20. 30. 40.]
[ 0. 10. 20. 30. 40.]


In [28]:
x = np.arange(1, 5)
print(x)
print(np.add.reduce(x)) # свертка суммы всего массива


[1 2 3 4]
10


In [30]:
x = np.arange(1, 10)
print(np.add.outer(x, x)) # квадратная матрица с результатами сложения попарно всех элементов


[[ 2  3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10 11]
 [ 4  5  6  7  8  9 10 11 12]
 [ 5  6  7  8  9 10 11 12 13]
 [ 6  7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14 15]
 [ 8  9 10 11 12 13 14 15 16]
 [ 9 10 11 12 13 14 15 16 17]
 [10 11 12 13 14 15 16 17 18]]
