In [ ]:
#при размерность данных >2, то используют иерархическую индексацию - мультииндекс

In [1]:
import numpy as np
import pandas as pd

index = [('city_1', 2010),
    ('city_1', 2020),
    ('city_2', 2010),
    ('city_2', 2020),
    ('city_3', 2010),
    ('city_3', 2020)]
population = [101,201,102,202,102,203]

pop = pd.Series(population, index = index)
print(pop)
print(pop[[i for i in pop.index if i[1] == 2020]])

(city_1, 2010)    101
(city_1, 2020)    201
(city_2, 2010)    102
(city_2, 2020)    202
(city_3, 2010)    102
(city_3, 2020)    203
dtype: int64
(city_1, 2020)    201
(city_2, 2020)    202
(city_3, 2020)    203
dtype: int64


In [2]:
index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index)
print(pop)
print(pop[:, 2020])

city_1  2010    101
        2020    201
city_2  2010    102
        2020    202
city_3  2010    102
        2020    203
dtype: int64
city_1    201
city_2    202
city_3    203
dtype: int64


In [3]:
pop_df = pop.unstack()
print(pop_df)
print(pop_df.stack())

        2010  2020
city_1   101   201
city_2   102   202
city_3   102   203
city_1  2010    101
        2020    201
city_2  2010    102
        2020    202
city_3  2010    102
        2020    203
dtype: int64


In [4]:
population = [101,1010,201,2010,102,1020,202,2020,102,1020,203,2030]
index = [('city_1', 2010, 1),
    ('city_1', 2010, 2),
    
    ('city_1', 2020, 1),
    ('city_1', 2020, 2),
    
    ('city_2', 2010, 1),
    ('city_2', 2010, 2),
    
    ('city_2', 2020, 1),
    ('city_2', 2020, 2),
    
    ('city_3', 2010, 1),
    ('city_3', 2010, 2),
    
    ('city_3', 2020, 1),
    ('city_3', 2020, 2)]
pop = pd.Series(population, index = index)
print(pop)

index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index) #по уровням
print(pop)

print(pop[:,2010])
print(pop[:,:,2])

(city_1, 2010, 1)     101
(city_1, 2010, 2)    1010
(city_1, 2020, 1)     201
(city_1, 2020, 2)    2010
(city_2, 2010, 1)     102
(city_2, 2010, 2)    1020
(city_2, 2020, 1)     202
(city_2, 2020, 2)    2020
(city_3, 2010, 1)     102
(city_3, 2010, 2)    1020
(city_3, 2020, 1)     203
(city_3, 2020, 2)    2030
dtype: int64
city_1  2010  1     101
              2    1010
        2020  1     201
              2    2010
city_2  2010  1     102
              2    1020
        2020  1     202
              2    2020
city_3  2010  1     102
              2    1020
        2020  1     203
              2    2030
dtype: int64
city_1  1     101
        2    1010
city_2  1     102
        2    1020
city_3  1     102
        2    1020
dtype: int64
city_1  2010    1010
        2020    2010
city_2  2010    1020
        2020    2020
city_3  2010    1020
        2020    2030
dtype: int64


In [5]:
pop_df = pop.unstack()

print(pop_df)
print(pop_df.stack())

               1     2
city_1 2010  101  1010
       2020  201  2010
city_2 2010  102  1020
       2020  202  2020
city_3 2010  102  1020
       2020  203  2030
city_1  2010  1     101
              2    1010
        2020  1     201
              2    2010
city_2  2010  1     102
              2    1020
        2020  1     202
              2    2020
city_3  2010  1     102
              2    1020
        2020  1     203
              2    2030
dtype: int64


In [7]:
index = [('city_1', 2010),
    ('city_1', 2020),
    ('city_2', 2010),
    ('city_2', 2020),
    ('city_3', 2010),
    ('city_3', 2020)]
population = [101,201,102,202,102,203]

pop = pd.Series(population, index = index)
print(pop)
index = pd.MultiIndex.from_tuples(index)
pop_df = pd.DataFrame({'total' : pop,
        'something' : [10,11,12,13,14,15,]})

print(pop_df)
print(pop_df['something'])

(city_1, 2010)    101
(city_1, 2020)    201
(city_2, 2010)    102
(city_2, 2020)    202
(city_3, 2010)    102
(city_3, 2020)    203
dtype: int64
                total  something
(city_1, 2010)    101         10
(city_1, 2020)    201         11
(city_2, 2010)    102         12
(city_2, 2020)    202         13
(city_3, 2010)    102         14
(city_3, 2020)    203         15
(city_1, 2010)    10
(city_1, 2020)    11
(city_2, 2010)    12
(city_2, 2020)    13
(city_3, 2010)    14
(city_3, 2020)    15
Name: something, dtype: int64


In [9]:
#мультииндексы:
# 1.список массивов которые задают значения индекса на каждом уровне 
i1 = pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]])
print(i1)

# 2.список кортежей, задающих значение индекса в каждой точке
i2 = pd.MultiIndex.from_tuples([('a', 1),('a', 2),('b', 1),('b', 2),])
print(i2)

# 3. декартово произведение обычных индексов
i3 = pd.MultiIndex.from_product([['a','b'],[1,2]])
print(i3)

# 4. описание внутреннего представления: levels, codes
i4 = pd.MultiIndex(levels = [['a','b'],[1,2]],codes = [[0,0,1,1], [0,1,0,1]])
print(i4)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )
MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )
MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )
MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )


In [10]:
# names for levels

data = {('city_1', 2010): 100,
    ('city_1', 2020): 200,
    ('city_2', 2010): 1001,
    ('city_2', 2020): 2001}

s = pd.Series(data)
print(s)
s.index.names = ['city','year']
print(s)

city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64
city    year
city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64


In [11]:
index = pd.MultiIndex.from_product([['city_1','city_2'],
                                    [2010,2020]],names = ['city','year'])
print(index)
columns = pd.MultiIndex.from_product(
    [['person_1','person_2', 'person_3'],['job1','job2','job3']],
    names = ['worker','job'])

rng = np.random.default_rng(1)
data = rng.random((4,9))
print(data)

data_df = pd.DataFrame(data, index=index, columns=columns)
print(data_df)

MultiIndex([('city_1', 2010),
            ('city_1', 2020),
            ('city_2', 2010),
            ('city_2', 2020)],
           names=['city', 'year'])
[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645
  0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331 0.32973172 0.7884287  0.30319483
  0.45349789 0.1340417  0.40311299]
 [0.20345524 0.26231334 0.75036467 0.28040876 0.48519097 0.9807372
  0.96165719 0.72478994 0.54122686]
 [0.2768912  0.16065201 0.96992541 0.51606859 0.11586561 0.62348976
  0.77668311 0.6130033  0.9172977 ]]
worker       person_1                      person_2                      \
job              job1      job2      job3      job1      job2      job3   
city   year                                                               
city_1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326   
       2020  0.027559  0.753513  0.538143  0.329732  0.788429  0.303195   
city_2 2010  0.203455  0.262313  0.750365  0.280409  

In [14]:
data = {('city_1', 2010): 100,
    ('city_1', 2020): 200,
    ('city_2', 2010): 1001,
    ('city_2', 2020): 2001,
    ('city_3', 2010): 10001,
    ('city_3', 2020): 20001,}
s = pd.Series(data)
s.index.names = ['city','year']

print(s['city_1',2010])
print(s['city_1'])

print(s.loc['city_1':'city_2'])
print(s[:,2010])

print(s[s>2000])

print(s.loc[['city_1','city_3']])

100
year
2010    100
2020    200
dtype: int64
city    year
city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64
city
city_1      100
city_2     1001
city_3    10001
dtype: int64
city    year
city_2  2020     2001
city_3  2010    10001
        2020    20001
dtype: int64
city    year
city_1  2010      100
        2020      200
city_3  2010    10001
        2020    20001
dtype: int64


In [15]:
#перегруппировка мультииндексов 
index = pd.MultiIndex.from_product([['a','c','b'],[1,2]])

data = pd.Series(rng.random(6), index = index)
data.index.names = ['char', 'int']

print(data)
# print(data['a':'b'])   индексы не отсортированы

data = data.sort_index()
print(data)
print(data['a':'b']) 

char  int
a     1      0.039593
      2      0.528589
c     1      0.459336
      2      0.062350
b     1      0.641328
      2      0.852633
dtype: float64
char  int
a     1      0.039593
      2      0.528589
b     1      0.641328
      2      0.852633
c     1      0.459336
      2      0.062350
dtype: float64
char  int
a     1      0.039593
      2      0.528589
b     1      0.641328
      2      0.852633
dtype: float64


In [16]:
population = [101,1010,201,2010,102,1020,202,2020,102,1020,203,2030]
index = [('city_1', 2010, 1),
    ('city_1', 2010, 2),
    
    ('city_1', 2020, 1),
    ('city_1', 2020, 2),
    
    ('city_2', 2010, 1),
    ('city_2', 2010, 2),
    
    ('city_2', 2020, 1),
    ('city_2', 2020, 2),
    
    ('city_3', 2010, 1),
    ('city_3', 2010, 2),
    
    ('city_3', 2020, 1),
    ('city_3', 2020, 2)]

pop = pd.Series(population, index=index)
print(pop)
i = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(i)

print(pop)
print(pop.unstack()) # dataframe

print(pop.unstack(level = 0)) # столбцом становится индекс city
print(pop.unstack(level = 1))
print(pop.unstack(level = 2))

(city_1, 2010, 1)     101
(city_1, 2010, 2)    1010
(city_1, 2020, 1)     201
(city_1, 2020, 2)    2010
(city_2, 2010, 1)     102
(city_2, 2010, 2)    1020
(city_2, 2020, 1)     202
(city_2, 2020, 2)    2020
(city_3, 2010, 1)     102
(city_3, 2010, 2)    1020
(city_3, 2020, 1)     203
(city_3, 2020, 2)    2030
dtype: int64
city_1  2010  1     101
              2    1010
        2020  1     201
              2    2010
city_2  2010  1     102
              2    1020
        2020  1     202
              2    2020
city_3  2010  1     102
              2    1020
        2020  1     203
              2    2030
dtype: int64
               1     2
city_1 2010  101  1010
       2020  201  2010
city_2 2010  102  1020
       2020  202  2020
city_3 2010  102  1020
       2020  203  2030
        city_1  city_2  city_3
2010 1     101     102     102
     2    1010    1020    1020
2020 1     201     202     203
     2    2010    2020    2030
          2010  2020
city_1 1   101   201
       2  1010  

In [17]:
# конктенация

x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
print(np.concatenate([x,y,z]))

x = [[1,2,3]]
y = [[4,5,6]]
z = [[7,8,9]]
print(np.concatenate([x,y,z]))
print(np.concatenate([x,y,z], axis=0))
print(np.concatenate([x,y,z], axis=1))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


In [18]:
# pandas

ser1 = pd.Series(['a','b','c'],index=[1,2,3])
ser2 = pd.Series(['d','e','f'],index=[4,5,6])

print(pd.concat([ser1,ser2]))

ser1 = pd.Series(['a','b','c'],index=[1,2,3])
ser2 = pd.Series(['d','e','f'],index=[1,2,6])

print(pd.concat([ser1,ser2], verify_integrity=False)) #не повторяются
print(pd.concat([ser1,ser2], ignore_index=True)) #свои индексы 
print(pd.concat([ser1,ser2], keys=['x','y']))

print(pd.concat([ser1,ser2], join='outer'))
print(pd.concat([ser1,ser2], join='inner'))

1    a
2    b
3    c
4    d
5    e
6    f
dtype: object
1    a
2    b
3    c
1    d
2    e
6    f
dtype: object
0    a
1    b
2    c
3    d
4    e
5    f
dtype: object
x  1    a
   2    b
   3    c
y  1    d
   2    e
   6    f
dtype: object
1    a
2    b
3    c
1    d
2    e
6    f
dtype: object
1    a
2    b
3    c
1    d
2    e
6    f
dtype: object
